In [1]:
import numpy as np
# electricity=np.array((4,7))
# rows hostels 1 to 7
# clolunms monday to sunday
# task a1
electricity=np.random.randint(120,650,28)
electricity=electricity.reshape(4,7)
print(electricity)

# task a2
print(electricity.shape,electricity.ndim,electricity.size,electricity.dtype)


[[164 358 343 235 428 123 162]
 [646 420 417 158 537 122 623]
 [286 144 261 391 609 643 563]
 [629 604 549 448 312 233 289]]
(4, 7) 2 28 int32


In [5]:
# task b2
print(electricity.mean(axis=1).reshape(4,1))
# hostel 4 has highest usage

# task b2

print(electricity.sum(axis=0))

# friday is day of max consumption


[[259.        ]
 [417.57142857]
 [413.85714286]
 [437.71428571]]
[1725 1526 1570 1232 1886 1121 1637]
