In [1]:
import numpy as np
import pandas as pd

In [2]:
prices=np.array([[1500],[3000],[5000]])

daily_sales=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

print(prices.ndim,prices.shape)
print(daily_sales.ndim,daily_sales.shape)

2 (3, 1)
2 (3, 4)


In [3]:
new_sales=daily_sales+2
print(new_sales)

# total reenue each day
total_day_revenue=prices*new_sales
print(total_day_revenue)


# multioplication not possible due to constraints

sqrt=np.sqrt(new_sales)
print(sqrt)


[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]
[[18000 25500 15000 21000]
 [21000 27000 18000 24000]
 [20000 25000 20000 30000]]
[[3.46410162 4.12310563 3.16227766 3.74165739]
 [2.64575131 3.         2.44948974 2.82842712]
 [2.         2.23606798 2.         2.44948974]]


In [4]:
Smartwatches=new_sales[0:1]
print(Smartwatches)
# row 1

#2 days
#2 columns

print()

sales_2_day=new_sales[0: ,0:2]
print(sales_2_day)


[[12 17 10 14]]

[[12 17]
 [ 7  9]
 [ 4  5]]


In [5]:
# task 3.3
# head 
# smartwatches
# speakers

speaker_on_thursday=new_sales[2:3, 2:3]
print(speaker_on_thursday)

# headphones and watch on mon tuesday

mon_tue=new_sales[0:2,0:2]
print(mon_tue)




[[4]]
[[12 17]
 [ 7  9]]


In [6]:
# task 4.1

# flatten dily sales to 1d

flatten_daily_sales=daily_sales.reshape(12,1)
print(flatten_daily_sales)
print()

# task 4.3 linspace 0 to 100 10 size
discount_percentage=np.linspace(0,100,10)
print(discount_percentage)

[[10]
 [15]
 [ 8]
 [12]
 [ 5]
 [ 7]
 [ 4]
 [ 6]
 [ 2]
 [ 3]
 [ 2]
 [ 4]]

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [7]:
# task 5.1
# Predicted_sales=np.random.randint(3,4)
Predicted_sales_=np.random.randint(0,20,12)
Predicted_sales=Predicted_sales_.reshape(3,4)
print(Predicted_sales)

# 5.2
random_5=np.random.randint(0,200,5)
print(random_5)

# 5.3



[[ 2  9  0 11]
 [13  7  7  8]
 [ 3  2  3 18]]
[106 195  18   6  98]
