In [1]:
import numpy as np
import time

In [2]:
size=100
py_list=list(range(size))
start= time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python time taken in secs {end-start}")

# arr=np.array([1, 5, 5, 1, 8, 0, 5])

np_arr=np.array(py_list)
start=time.time()  
sq_arr=np_arr ** 2
end=time.time()
print(f"time taken by numpy {end-start}")

python time taken in secs 0.00010943412780761719
time taken by numpy 6.651878356933594e-05


In [3]:
# print(arr,type(arr))
import sys

print(f"python list size= {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy arr size= {np_arr.nbytes} bytes")

 

python list size= 85600 bytes
numpy arr size= 800 bytes


In [4]:
# creating numpy array using lists

arr1=np.array([1,5,6,7,9,7,])
arr2=np.array([1,6,4,"jayant"])
print(arr1,type(arr1),arr1.dtype,arr1.shape)
print(arr2,type(arr2),arr2.dtype,arr2.shape)


# 2d list then 2d array

arr2d=np.array([[1,2],[4,5],[7,8]])
print(arr2d, type(arr2d), arr2d.dtype, arr2d.shape)
# 3,3 means dimension row,column




 

[1 5 6 7 9 7] <class 'numpy.ndarray'> int64 (6,)
['1' '6' '4' 'jayant'] <class 'numpy.ndarray'> <U21 (4,)
[[1 2]
 [4 5]
 [7 8]] <class 'numpy.ndarray'> int64 (3, 2)


In [5]:
# creating arrays using built in methods
arr3=np.zeros((2,3), dtype="int32")#prefill
print(arr3, arr3.shape)

arr4=np.ones((5,),dtype="int32")
print(arr4, arr4.shape)

arr5=np.full((2,3),20)
print(arr5,arr5.dtype,arr5.shape)

# creationg identity matrix
arr6=np.eye(3,dtype="int32")
print(arr6,type(arr6),arr6.shape,arr6.dtype)

# arr in range with jump by 2
arr7=np.arange(0,11,2)
print(arr7,arr7.shape)

# evenly spaced array
arr8=np.linspace(0,3,6) #linspace(start,end,no of elements)
print(arr8)



[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[20 20 20]
 [20 20 20]] int64 (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'> (3, 3) int32
[ 0  2  4  6  8 10] (6,)
[0.  0.6 1.2 1.8 2.4 3. ]


In [6]:
# properties numpy array
arr1=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(arr1.ndim)
# arr.shape   dimensions output
print(arr1.size)
print(arr1.dtype)
 # no of dimension
print(arr1.ndim)  #2 bcz its 2d array

# typecasting
float_arr=arr1.astype(np.float64)
print(float_arr,float_arr.dtype,float_arr.size,float_arr.ndim)



2
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]] float64 9 2


In [7]:
# inportant operation on numpy arrays 
 # 1 2 3 
 # 4 5 6

# to

#  1 2 
#  3 4
#  5 6

arr=np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.size,reshaped.dtype,reshaped.ndim)

flattened= arr.flatten()         #2d to 1d

print(flattened,flattened.size,flattened.shape,flattened.ndim)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] 6 int64 2
[1 2 3 4 5 6] 6 (6,) 1


In [8]:
# indexing on numpy arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[-1])
# indexing in 2d arrays
arr1=np.array([[1,2,3,0],[4,5,6,1],[7,8,9,2]])
print(arr1[0,2])
print()
# doing fancy indexing
idx=[1,3,5]
print(arr[idx])
print()
# boolean indexing
print(arr[arr>4])
print()
print(arr>4)
print()
# slicing array
print(arr[0:5:2])
# slice step needs to be understood
print(arr1[1:3,2:4])


      

1
2
3
7
3

[2 4 6]

[5 6 7]

[False False False False  True  True  True]

[1 3 5]
[[6 1]
 [9 2]]


In [9]:
a=np.ones((2,3))
print(a)
b=np.arange(0,10,2)
print(b)

c=np.linspace(0,100,6)
print(c)
print(c,c.ndim,c.dtype,c.shape,c.size)

intc=c.astype("int32")
print(intc.dtype)


# unsafe way to copy 
# d=c wrong way

d=c.copy()#correct way
d[0]=25

print(c)
print(d)
# resulted in change in parwent array flaged

# how to do correctly use 
print()
print(c**2)
print()
print(d+5)

print(np.std(c))
print(np.median(c))
# print(np.log(c))
print(np.prod(c))






[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[  0.  20.  40.  60.  80. 100.]
[  0.  20.  40.  60.  80. 100.] 1 float64 (6,) 6
int32
[  0.  20.  40.  60.  80. 100.]
[ 25.  20.  40.  60.  80. 100.]

[    0.   400.  1600.  3600.  6400. 10000.]

[ 30.  25.  45.  65.  85. 105.]
34.15650255319866
50.0
0.0


In [10]:
# hadmard product
# Element wise emultiplication
#broadcasting
# compare maths and ector broadcasting in numpy

# examples of broadcasting 

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# broadcasting rules

# numpy automatically expands smaller arrays
arr=np.array([1,2,3,4])
print(arr+10)



[11 12 13 14]


In [11]:
mat=np.array([[1,2,3],[4,5,6]])

print(mat*10)


[[10 20 30]
 [40 50 60]]


In [12]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


In [13]:
# Matrix Multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.dot(a,b))


[[19 22]
 [43 50]]


In [14]:
# Transpose matrix
print(a.T)

[[1 3]
 [2 4]]


In [15]:
# random module
c=np.random.rand(5)
print(c)
d=np.random.rand(3,3)#dimension
print(d)
e=np.random.randint(1,100,10)#(start,end,no of elements=i.e size)
print(e)

[0.23663331 0.21641741 0.31414978 0.33127138 0.60804985]
[[0.87965423 0.12732002 0.15130027]
 [0.07723629 0.65854889 0.9155007 ]
 [0.36761267 0.65992257 0.63909563]]
[16 65 58  4  1 11 84  9 35 85]


In [16]:
# Reshaping arrays
arr=np.arange(12)
print(arr.reshape(3,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# axes in numpy

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))# represents column sum but axis =0 is row vertically
print(np.sum(arr,axis=1))#represents row wise sum but axis=1 represents column

[5 7 9]
[ 6 15]


In [18]:
# where in numpy
arr=np.array([10,-5,20,-3,15])
result=np.where(arr<0,0,arr)#(condition,true,else)
print(result)

[10  0 20  0 15]


In [19]:
result=np.where(arr%2!=0,-1,arr)
print(result) 

[10 -1 20 -1 -1]


In [22]:
data=np.array([10,20,30,40,50])
mean_data=np.mean(data)
result=np.where(data>mean_data,mean_data,data)
print(result)



[10. 20. 30. 30. 30.]
